### ISSUE TITLE
实验三实验验收内容要求错误

### ISSUE THREAD

**Issue by yihuajack** [NJU-ProjectN/dlco-lecture-note#3]
https://nju-projectn.github.io/dlco-lecture-note/exp/03.html
在实验三——加法器与ALU的实验验收内容部分：“执行逻辑操作时不需要考虑overflow和溢出”，overflow与溢出表示同一个意思，这里是否指溢出和进位？

**Comment by sashimi-yzh** [comment]
已修改, 感谢指出!
